name: Qseer application

on:
  push:
<<<<<<< Updated upstream:.github/workflows/deploy.yml
    branches:
      - dev

  # Allows you to run this workflow manually from the Actions tab
=======
    branches: [ "Dev" ]
>>>>>>> Stashed changes:Front-end-Admin/.github/workflows/deploy.yml
  workflow_dispatch:

permissions:
  contents: read
jobs:
  build:
    runs-on: self-hosted
    environment: Production
    steps:
<<<<<<< Updated upstream:.github/workflows/deploy.yml
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
=======
    - name: Fetch latest commit
      uses: actions/checkout@v4
    - name: Build app
      run: docker compose up --force-recreate --build --detach
    - name: Check if app is running
      id: checkAlive
      run: sleep 5 && docker compose ps --services --status=exited | grep -v '\b\b'
    - name: Show failed logs
      if: failure() && steps.checkAlive.outcome == 'failure'
      run: docker compose logs
>>>>>>> Stashed changes:Front-end-Admin/.github/workflows/deploy.yml
